-- =====================================================
-- SQL FIX: Supabase Duplicate Key Error (materials_pkey)
-- Error: duplicate key value violates unique constraint
-- Key (id)=(0) already exists
-- =====================================================

-- 1. ลบ row id=0 ที่ผิดปกติออก (ถ้ามี)
-- ระวัง: ถ้า row id=0 มีข้อมูลสำคัญ ให้สำรองก่อน
DELETE FROM materials WHERE id = 0;

-- 2. สร้าง sequence ถ้ายังไม่มี (สำหรับ auto-increment)
-- ตรวจสอบว่ามี sequence หรือไม่ ถ้าไม่มีให้สร้าง
DO $$
BEGIN
  -- สำหรับ PostgreSQL ที่ใช้ SERIAL/IDENTITY
  -- sequence จะมีชื่อแบบ: materials_id_seq
  
  -- ตรวจสอบว่า sequence มีอยู่หรือไม่
  IF EXISTS (
    SELECT 1 FROM pg_class 
    WHERE relkind = 'S' 
    AND relname = 'materials_id_seq'
  ) THEN
    -- ตั้งค่า sequence ให้เริ่มจากค่า max id + 1
    EXECUTE format(
      'SELECT setval(%L, COALESCE((SELECT MAX(id) FROM materials), 0) + 1)',
      'materials_id_seq'
    );
  END IF;
END
$$;

-- 3. ถ้าใช้ IDENTITY column (GENERATED BY DEFAULT AS IDENTITY)
-- ให้ reset identity ให้เริ่มจากค่า max id + 1
SELECT setval(
  pg_get_serial_sequence('materials', 'id'),
  COALESCE((SELECT MAX(id) FROM materials), 0) + 1
);

-- 4. ตรวจสอบว่า id ถัดไปจะเป็นอะไร
SELECT 
  'Next ID will be: ' || nextval('materials_id_seq') AS next_id;

-- =====================================================
-- ALTERNATIVE FIX: ถ้ายังไม่ได้ ให้ลองวิธีนี้
-- =====================================================

-- วิธีที่ 2: ใช้ UUID แทน auto-increment (แนะนำสำหรับ production)
-- เพิ่ม column uuid ใหม่ และ migrate ข้อมูล
/*
ALTER TABLE materials 
ADD COLUMN uuid UUID DEFAULT gen_random_uuid();

-- สร้าง index บน uuid
CREATE INDEX idx_materials_uuid ON materials(uuid);
*/

-- วิธีที่ 3: Fix ถ้าใช้ Supabase มี foreign key constraints
-- ตรวจสอบว่ามี reference จากตารางอื่นหรือไม่
SELECT 
  tc.table_schema, 
  tc.table_name, 
  kcu.column_name,
  ccu.table_name AS foreign_table_name,
  ccu.column_name AS foreign_column_name
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
  ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage AS ccu
  ON ccu.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY'
AND ccu.table_name = 'materials';
