-- ============================================
-- SUPABASE SQL SETUP — ระบบร้านป้ายอิงค์เจ็ท
-- ============================================
-- คัดลอกทั้งหมดนี้ไปรันใน Supabase > SQL Editor
-- Version: 2026-04-06

-- 1. ตารางสาขา (Branches)
CREATE TABLE IF NOT EXISTS branches (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    phone TEXT,
    logo_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ตารางโปรไฟล์ผู้ใช้งาน (User Profiles)
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    role TEXT DEFAULT 'staff',
    branch_id TEXT REFERENCES branches(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ตารางหมวดหมู่วัสดุ (Categories)
CREATE TABLE IF NOT EXISTS categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ตารางคู่ค้า/ร้านค้าวัสดุ (Suppliers)
CREATE TABLE IF NOT EXISTS suppliers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ตารางวัสดุคงคลัง (Materials)
CREATE TABLE IF NOT EXISTS materials (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id TEXT REFERENCES branches(id),
    name TEXT NOT NULL,
    category_id INT REFERENCES categories(id),
    unit TEXT NOT NULL,
    current_stock FLOAT8 DEFAULT 0,
    min_stock_level FLOAT8 DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ตารางบันทึกการซื้อวัสดุเข้า (Purchase Transactions)
CREATE TABLE IF NOT EXISTS purchase_transactions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id TEXT REFERENCES branches(id),
    material_id INT REFERENCES materials(id) ON DELETE CASCADE,
    supplier_id INT REFERENCES suppliers(id),
    quantity FLOAT8 NOT NULL,
    total_price FLOAT8 NOT NULL,
    unit_cost FLOAT8 NOT NULL,
    purchase_date TIMESTAMPTZ DEFAULT NOW(),
    receipt_no TEXT
);

-- 7. ตารางบันทึกการเบิกวัสดุ (Usage Transactions)
CREATE TABLE IF NOT EXISTS usage_transactions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id TEXT REFERENCES branches(id),
    material_id INT REFERENCES materials(id) ON DELETE CASCADE,
    job_id INT,
    quantity_used FLOAT8 NOT NULL,
    usage_date TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT
);

-- 7.5. ตารางรายจ่ายทั่วไป (Expenses)
CREATE TABLE IF NOT EXISTS expenses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id TEXT REFERENCES branches(id),
    user_id UUID REFERENCES auth.users(id),
    title TEXT NOT NULL,
    amount FLOAT8 NOT NULL,
    expense_date TIMESTAMPTZ DEFAULT NOW(),
    note TEXT
);

-- 8. ตารางบันทึกคำสั่งงาน/บิล (Orders)
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    branch_id TEXT REFERENCES branches(id),
    user_id UUID,
    total FLOAT8 DEFAULT 0,
    status TEXT DEFAULT 'completed',
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. ตารางบันทึกกิจกรรม (Logs)
CREATE TABLE IF NOT EXISTS logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    action TEXT NOT NULL,
    detail TEXT,
    branch_id TEXT REFERENCES branches(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== ข้อมูลเริ่มต้น (Default Seed Data) =====
INSERT INTO categories (name) VALUES
  ('ไวนิล/สติ๊กเกอร์'),
  ('หมึกพิมพ์'),
  ('โครง/วัสดุประกอบ'),
  ('อื่นๆ')
ON CONFLICT DO NOTHING;

INSERT INTO suppliers (name, contact) VALUES
  ('ร้านทั่วไป (ไม่ระบุ)', '-')
ON CONFLICT DO NOTHING;
