-- ============================================================
-- SUPABASE SQL SETUP — ระบบจัดการสต็อก (Stock Management)
-- ============================================================
-- Version: 2026-04-29 (Full Refactor — Single-Shop, 3 Roles)
-- วิธีใช้: Copy ทั้งหมดไปรันใน Supabase > SQL Editor
-- ============================================================

-- ========================================
-- SECTION 1: DROP ตารางเก่าทั้งหมด
-- ========================================

DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS usage_transactions CASCADE;
DROP TABLE IF EXISTS purchase_transactions CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS branches CASCADE;

-- Drop new tables too (in case re-running)
DROP TABLE IF EXISTS stock_withdrawals CASCADE;
DROP TABLE IF EXISTS stock_purchases CASCADE;
DROP TABLE IF EXISTS stock_items CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- ========================================
-- SECTION 2: สร้างตารางใหม่
-- ========================================

-- 1. ตารางผู้ใช้งาน (Users)
-- เชื่อมกับ auth.users ของ Supabase
CREATE TABLE users (
    id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email      TEXT NOT NULL,
    role       TEXT NOT NULL DEFAULT 'technician'
               CHECK (role IN ('admin', 'accountant', 'technician')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_email ON users(email);

-- 2. ตารางสินค้าคงคลัง (Stock Items)
CREATE TABLE stock_items (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    unit       TEXT NOT NULL,
    quantity   FLOAT8 NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_stock_items_name ON stock_items(name);

-- 3. ตารางบันทึกการซื้อเข้า (Stock Purchases)
-- บัญชีกรอกข้อมูลการซื้อสินค้าเข้าสต็อก
CREATE TABLE stock_purchases (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id        INT NOT NULL REFERENCES stock_items(id) ON DELETE CASCADE,
    quantity       FLOAT8 NOT NULL,
    price_per_unit FLOAT8 NOT NULL DEFAULT 0,
    total_price    FLOAT8 NOT NULL DEFAULT 0,
    supplier       TEXT DEFAULT '',
    purchased_by   UUID REFERENCES auth.users(id),
    purchased_at   TIMESTAMPTZ DEFAULT NOW(),
    note           TEXT DEFAULT ''
);

CREATE INDEX idx_purchases_item ON stock_purchases(item_id);
CREATE INDEX idx_purchases_by ON stock_purchases(purchased_by);
CREATE INDEX idx_purchases_at ON stock_purchases(purchased_at DESC);

-- 4. ตารางบันทึกการเบิกของ (Stock Withdrawals)
-- ช่างกรอกข้อมูลการเบิกสินค้าออกจากสต็อก
CREATE TABLE stock_withdrawals (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id       INT NOT NULL REFERENCES stock_items(id) ON DELETE CASCADE,
    quantity      FLOAT8 NOT NULL,
    purpose       TEXT DEFAULT '',
    withdrawn_by  UUID REFERENCES auth.users(id),
    withdrawn_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_withdrawals_item ON stock_withdrawals(item_id);
CREATE INDEX idx_withdrawals_by ON stock_withdrawals(withdrawn_by);
CREATE INDEX idx_withdrawals_at ON stock_withdrawals(withdrawn_at DESC);


-- ========================================
-- SECTION 3: RLS (Row Level Security)
-- ========================================

ALTER TABLE users             ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_items       ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_purchases   ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_withdrawals ENABLE ROW LEVEL SECURITY;

-- Backend ใช้ service_role key ซึ่งข้าม RLS โดยอัตโนมัติ
-- RLS policies ด้านล่างใช้สำหรับ client-side access (ถ้ามี)

-- Allow service role to do everything (backend)
-- No additional policies needed since backend uses service_role key


-- ========================================
-- SECTION 4: Fix Sequences (ถ้ารันซ้ำ)
-- ========================================

SELECT setval(
  pg_get_serial_sequence('stock_items', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM stock_items)
);

SELECT setval(
  pg_get_serial_sequence('stock_purchases', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM stock_purchases)
);

SELECT setval(
  pg_get_serial_sequence('stock_withdrawals', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM stock_withdrawals)
);


-- ========================================
-- SECTION 5: ตารางเพิ่มเติม (Phase 2)
-- ========================================

-- 5. ตารางสาขา (Branches) — ใช้ในใบเสนอราคา
CREATE TABLE IF NOT EXISTS branches (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    address    TEXT DEFAULT '',
    phone      TEXT DEFAULT '',
    tax_id     TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE branches ENABLE ROW LEVEL SECURITY;

-- 6. ตารางใบเสนอราคา (Quotations)
CREATE TABLE IF NOT EXISTS quotations (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_no     TEXT NOT NULL UNIQUE,
    branch_id        INT REFERENCES branches(id),
    customer_name    TEXT DEFAULT '',
    customer_address TEXT DEFAULT '',
    customer_tax_id  TEXT DEFAULT '',
    items            JSONB NOT NULL DEFAULT '[]',
    total_amount     FLOAT8 DEFAULT 0,
    total_in_words   TEXT DEFAULT '',
    status           TEXT DEFAULT 'draft'
                     CHECK (status IN ('draft','sent','approved')),
    created_by       UUID REFERENCES auth.users(id),
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_quotations_no ON quotations(quotation_no);
CREATE INDEX idx_quotations_status ON quotations(status);
ALTER TABLE quotations ENABLE ROW LEVEL SECURITY;

-- 7. ตารางการดำเนินงาน (Jobs / Kanban)
CREATE TABLE IF NOT EXISTS jobs (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          TEXT NOT NULL,
    description    TEXT DEFAULT '',
    status         TEXT NOT NULL DEFAULT 'รับงาน/ทำแบบ'
                   CHECK (status IN (
                     'รับงาน/ทำแบบ',
                     'เตรียมสี/วัสดุ',
                     'ลงมือสกรีน',
                     'อบแห้ง/QC',
                     'งานเสร็จพร้อมส่ง'
                   )),
    payment_status TEXT NOT NULL DEFAULT 'unpaid'
                   CHECK (payment_status IN ('unpaid','deposit','paid')),
    assigned_to    UUID REFERENCES auth.users(id),
    created_by     UUID REFERENCES auth.users(id),
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_jobs_status ON jobs(status);
CREATE INDEX idx_jobs_payment ON jobs(payment_status);
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- Fix sequences for new tables
SELECT setval(
  pg_get_serial_sequence('branches', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM branches)
);
SELECT setval(
  pg_get_serial_sequence('quotations', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM quotations)
);
SELECT setval(
  pg_get_serial_sequence('jobs', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM jobs)
);


-- ========================================
-- SECTION 5.1: Phase 2.1 Patches
-- ========================================
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS price FLOAT8 DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS quotation_id INT REFERENCES quotations(id);


-- ========================================
-- SECTION 6: Role Setup (app_metadata)
-- ========================================
-- ตั้ง Role ผ่าน Supabase Dashboard > Authentication > Users
-- เลือก user > แก้ไข app_metadata:
--
-- สำหรับ Admin:        { "role": "admin" }
-- สำหรับ Accountant:   { "role": "accountant" }
-- สำหรับ Technician:   { "role": "technician" }

