-- ============================================================
-- SUPABASE SQL SETUP — ระบบร้านป้ายอิงค์เจ็ท (Multi-Branch)
-- ============================================================
-- Version: 2026-04-07 (Consolidated - replaces fix_duplicate_key.sql files)
-- วิธีใช้: Copy ทั้งหมดไปรันใน Supabase > SQL Editor
-- รัน Section ทีละส่วน หรือทั้งหมดในครั้งเดียว
-- ============================================================

-- ========================================
-- SECTION 1: สร้างตาราง (CREATE TABLES)
-- ========================================

-- 1. ตารางสาขา (Branches)
CREATE TABLE IF NOT EXISTS branches (
    id   TEXT PRIMARY KEY,        -- format: BR-xxxxxxxx
    name TEXT NOT NULL,
    address  TEXT,
    phone    TEXT,
    logo_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ตารางโปรไฟล์ผู้ใช้งาน (User Profiles)
CREATE TABLE IF NOT EXISTS user_profiles (
    id        UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email     TEXT,
    full_name TEXT,
    role      TEXT DEFAULT 'staff',   -- 'superadmin' | 'admin' | 'staff'
    branch_id TEXT REFERENCES branches(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ตารางหมวดหมู่วัสดุ (Categories)
CREATE TABLE IF NOT EXISTS categories (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ตารางคู่ค้า / ร้านค้าวัสดุ (Suppliers)
CREATE TABLE IF NOT EXISTS suppliers (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT NOT NULL,
    contact TEXT,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ตารางวัสดุคงคลัง (Materials / Stock)
CREATE TABLE IF NOT EXISTS materials (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id      TEXT REFERENCES branches(id),
    name           TEXT NOT NULL,
    category_id    INT  REFERENCES categories(id),
    unit           TEXT NOT NULL,
    current_stock  FLOAT8 DEFAULT 0,
    min_stock_level FLOAT8 DEFAULT 0,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW()
);

-- Index สำหรับ query เร็วขึ้น
CREATE INDEX IF NOT EXISTS idx_materials_branch_id ON materials(branch_id);
CREATE INDEX IF NOT EXISTS idx_materials_name      ON materials(name);

-- 6. ตารางบันทึกการซื้อวัสดุเข้า (Purchase Transactions)
CREATE TABLE IF NOT EXISTS purchase_transactions (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id     TEXT    REFERENCES branches(id),
    material_id   INT     REFERENCES materials(id) ON DELETE CASCADE,
    supplier_id   INT     REFERENCES suppliers(id),
    quantity      FLOAT8  NOT NULL,
    total_price   FLOAT8  NOT NULL,
    unit_cost     FLOAT8  NOT NULL,
    purchase_date TIMESTAMPTZ DEFAULT NOW(),
    receipt_no    TEXT
);

CREATE INDEX IF NOT EXISTS idx_purchase_branch    ON purchase_transactions(branch_id);
CREATE INDEX IF NOT EXISTS idx_purchase_material  ON purchase_transactions(material_id);

-- 7. ตารางบันทึกการเบิกวัสดุ (Usage Transactions)
CREATE TABLE IF NOT EXISTS usage_transactions (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    TEXT   REFERENCES branches(id),
    material_id  INT    REFERENCES materials(id) ON DELETE CASCADE,
    job_id       INT,
    quantity_used FLOAT8 NOT NULL,
    usage_date   TIMESTAMPTZ DEFAULT NOW(),
    notes        TEXT
);

-- 8. ตารางรายจ่ายทั่วไป (Expenses)
CREATE TABLE IF NOT EXISTS expenses (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    TEXT  REFERENCES branches(id),
    user_id      UUID  REFERENCES auth.users(id),
    title        TEXT  NOT NULL,
    amount       FLOAT8 NOT NULL,
    expense_date TIMESTAMPTZ DEFAULT NOW(),
    note         TEXT
);

CREATE INDEX IF NOT EXISTS idx_expenses_branch   ON expenses(branch_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date     ON expenses(expense_date);

-- 9. ตารางบันทึกคำสั่งงาน / บิล (Orders)
CREATE TABLE IF NOT EXISTS orders (
    id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    branch_id TEXT  REFERENCES branches(id),
    user_id   UUID,
    total     FLOAT8 DEFAULT 0,
    payment   TEXT   DEFAULT 'โอนเงิน',   -- 'โอนเงิน' | 'เงินสด'
    status    TEXT   DEFAULT 'completed',
    note      TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_branch    ON orders(branch_id);
CREATE INDEX IF NOT EXISTS idx_orders_created   ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_user      ON orders(user_id);

-- 10. ตารางบันทึกกิจกรรม (Activity Logs)
CREATE TABLE IF NOT EXISTS logs (
    id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id   UUID REFERENCES auth.users(id),
    action    TEXT NOT NULL,
    detail    TEXT,
    branch_id TEXT REFERENCES branches(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ========================================
-- SECTION 2: ข้อมูลเริ่มต้น (Seed Data)
-- ========================================

INSERT INTO categories (name) VALUES
  ('ไวนิล/สติ๊กเกอร์'),
  ('หมึกพิมพ์'),
  ('โครง/วัสดุประกอบ'),
  ('อื่นๆ')
ON CONFLICT DO NOTHING;

INSERT INTO suppliers (name, contact) VALUES
  ('ร้านทั่วไป (ไม่ระบุ)', '-')
ON CONFLICT DO NOTHING;


-- ========================================
-- SECTION 3: แก้ไข Sequence (Fix Duplicate Key)
-- ========================================
-- รัน section นี้ถ้าพบ Error: "duplicate key value violates unique constraint"
-- (รวมเนื้อหาจาก fix_duplicate_key.sql เดิม)

-- แก้ sequence ของ materials
SELECT setval(
  pg_get_serial_sequence('materials', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM materials)
);

-- แก้ sequence ของ purchase_transactions
SELECT setval(
  pg_get_serial_sequence('purchase_transactions', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM purchase_transactions)
);

-- แก้ sequence ของ usage_transactions
SELECT setval(
  pg_get_serial_sequence('usage_transactions', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM usage_transactions)
);

-- แก้ sequence ของ expenses
SELECT setval(
  pg_get_serial_sequence('expenses', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM expenses)
);

-- แก้ sequence ของ categories
SELECT setval(
  pg_get_serial_sequence('categories', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM categories)
);

-- แก้ sequence ของ suppliers
SELECT setval(
  pg_get_serial_sequence('suppliers', 'id'),
  (SELECT COALESCE(MAX(id), 0) + 1 FROM suppliers)
);


-- ========================================
-- SECTION 4: Role and Metadata Setup
-- ========================================
-- ตั้ง Role ผ่าน Supabase Dashboard > Authentication > Users
-- เลือก user > แก้ไข app_metadata:
--
-- สำหรับ Superadmin (เข้าถึงได้ทุกสาขา):
-- {
--   "role": "superadmin",
--   "branch_id": ""
-- }
--
-- สำหรับ Staff (เข้าถึงได้เฉพาะสาขาตัวเอง):
-- {
--   "role": "staff",
--   "branch_id": "BR-xxxxxxxx"
-- }


-- ========================================
-- SECTION 5: RLS Policies (Row Level Security)
-- ========================================
-- เปิด RLS เพื่อให้ staff เห็นเฉพาะข้อมูลสาขาตัวเอง
-- (Optional - Backend ของเราจัดการ filter แล้ว แต่ RLS เพิ่ม layer ของ security)

-- Enable RLS
ALTER TABLE orders           ENABLE ROW LEVEL SECURITY;
ALTER TABLE materials        ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses         ENABLE ROW LEVEL SECURITY;

-- Policy: Superadmin เห็นทุกอย่าง
-- (ใช้ service role key ใน backend จะข้าม RLS โดยอัตโนมัติ)

-- Policy: staff/admin เห็นเฉพาะสาขาตัวเอง (ผ่าน JWT claims)
-- หมายเหตุ: Backend ใช้ service_role key ซึ่งข้าม RLS ดังนั้น
-- การ filter จะทำที่ handler level แทนที่จะใช้ RLS policies


-- ========================================
-- SECTION 6: เพิ่ม Column ถ้าขาดในตาราง
-- ========================================
-- รันนี้ถ้าตาราง orders เดิมไม่มี payment column:
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'orders' AND column_name = 'payment'
  ) THEN
    ALTER TABLE orders ADD COLUMN payment TEXT DEFAULT 'โอนเงิน';
  END IF;
END $$;
